### ISSUE TITLE
pod install failure

### ISSUE THREAD

**Issue by GaRUi** [colendi-project/ColendiWebViewSDK-IOS#1]
```
% pod install    
Analyzing dependencies
[!] Unable to find a specification for `ColendiWebView`
```

cocoapods install via brew , and repository updated many times.
macOS Monterey M1 chip.

**Comment by uygar** [comment]
We updated our README, you can install repository using 'ColendiWebViewSDK'

**Comment by GaRUi** [comment]
Thanks. It works now.

`pod install
Analyzing dependencies
Downloading dependencies
Installing ColendiWebViewSDK (1.0.1)
Installing OpenSSL-Universal (1.1.1900)
Installing lottie-ios (3.3.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use colendiTest.xcworkspace for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.`
